### ISSUE TITLE
Invalid header line detected

### ISSUE THREAD

**Issue by falco-knapp** [Inxmail/inx_magento2#49]
A customer reported the following issue:

> During loading of the attribute-mapping of field  _Inxmail Professional_ **_recipient_** the generic error message  "**Invalid header line detected**" appeared.
> 

There is no evidence, that the issue is related with Inxmail Professional. The error message seems to be quite related to Magento:
https://www.google.com/search?q=Invalid+header+line+detected

**Stack-Trace:**
`#0 /Users/user/Workspace/magento2/customer/project/src/vendor/inxmail/magento2-module/Model/Api/ApiClient.php(350): Zend_Http_Response::extractHeaders('HTTP/2 200 \r\nda...')
#1 /Users/user/Workspace/magento2/customer/project/src/vendor/inxmail/magento2-module/Model/Request/RequestRecipientAttributes.php(69): Flagbit\Inxmail\Model\Api\ApiClient->getResource('', '', NULL, NULL)
#2 /Users/user/Workspace/magento2/customer/project/src/vendor/inxmail/magento2-module/Block/Adminhtml/System/Config/AttribSelectInx.php(64): Flagbit\Inxmail\Model\Request\RequestRecipientAttributes->sendRequest()
#3 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/AbstractBlock.php(667): Flagbit\Inxmail\Block\Adminhtml\System\Config\AttribSelectInx->_toHtml()
#4 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(213): Magento\Framework\View\Element\AbstractBlock->toHtml()
#5 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/view/adminhtml/templates/system/config/form/field/array.phtml(54): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->renderCellTemplate('inxAttrib')
#6 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Users/user...')
#7 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Flagbit\Inxmail\Block\Adminhtml\System\Config\AttributeMapping), '/Users/user...', Array)
#8 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/Users/user...')
#9 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#10 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(262): Magento\Backend\Block\Template->_toHtml()
#11 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(116): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->_toHtml()
#12 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Field.php(78): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->_getElementHtml(Object(Magento\Framework\Data\Form\Element\Text))
#13 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Field.php(52): Magento\Config\Block\System\Config\Form\Field->_renderValue(Object(Magento\Framework\Data\Form\Element\Text))
#14 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(459): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Text))
#15 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form/Element/Text.php(41): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#16 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(473): Magento\Framework\Data\Form\Element\Text->getHtml()
#17 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(86): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#18 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(66): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#19 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(459): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#20 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form/Element/AbstractElement.php(473): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#21 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form.php(325): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#22 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/Data/Form.php(340): Magento\Framework\Data\Form->toHtml()
#23 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-backend/Block/Widget/Form.php(101): Magento\Framework\Data\Form->getHtml()
#24 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#25 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Users/user...')
#26 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/Users/user...', Array)
#27 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/Users/user...')
#28 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#29 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#30 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#31 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#32 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#33 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#34 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#35 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#36 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#37 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Users/user...')
#38 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/Users/user...', Array)
#39 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/Users/user...')
#40 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#41 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#42 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#43 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#44 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#45 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#46 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#47 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#48 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#49 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#50 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#51 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#52 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#53 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#54 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#55 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#56 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#57 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#58 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#59 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#60 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#61 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#62 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#63 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#64 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#65 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#66 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#67 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#68 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#69 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#70 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#71 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#72 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#73 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#74 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#75 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#76 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#77 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#78 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#79 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#80 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#81 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#82 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#83 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#84 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#85 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#86 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#87 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#88 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#89 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#90 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#91 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#92 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#93 /Users/user/Workspace/magento2/customer/project/src/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#94 /Users/user/Workspace/magento2/customer/project/src/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#95 /Users/user/Workspace/magento2/customer/project/src/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#96 /Users/userffp/.composer/vendor/thirdparty/valet-plus/server.php(131): require('/Users/user...')
#97 {main}
`

**Comment by falco-knapp** [comment]
Additional Information:
Issue exists apparently with:
PHP Version 7.0 
PHP Version 7.1 
Magento Version 2.2.7.
